ALTER TABLE game
DROP COLUMN IF EXISTS data;

ALTER TABLE genre
DROP COLUMN IF EXISTS data;

ALTER TABLE theme
DROP COLUMN IF EXISTS data;

ALTER TABLE alt_name
DROP COLUMN IF EXISTS data;

ALTER TABLE collection
DROP COLUMN IF EXISTS data;

ALTER TABLE website
DROP COLUMN IF EXISTS data;
